SECRET_KEY = 'MY-SECRET-KEY'
MIXPANEL_TOKEN = 'MY-MIXPANEL-TOKEN'
MIXPANEL_SUPPRESS_SEND = True

CDN_SCHEME = 'MY-CDN-SCHEME-OR-NIL'
CDN_DOMAIN = 'MY-CDN-DOMAIN'
CDN_VERSION = 'MY-CDN-VERSION-PREFIX'

CONTACT_EMAIL = 'MY-APP-CONTACT-EMAIL'
DEBUG_EMAIL = 'MY-DEBUG-EMAIL'

APP_CONFIG = {
    'DEBUG': False,
    'TESTING': False
}

MAIL_SETTINGS = {
    'MAIL_SERVER': 'MY-SMTP-SERVER',
    'MAIL_PORT': '465',
    'MAIL_USE_TLS': True,
    'MAIL_USERNAME': 'MY-SMTP-USERNAME',
    'MAIL_PASSWORD': 'MY-SMTP-PASSWORD',
    'MAIL_DEFAULT_SENDER': 'MY-APP-EMAIL-ADDRESS',
    'MAIL_SUPPRESS_SEND': True
}

SENTRY_SETTINGS = {
    'SENTRY_DSN': 'MY-SENTRY-DSN'
}

DB_SETTINGS = {
    'HOST': 'MY-DB-HOSTNAME',
    'USER': 'MY-DB-USERNAME',
    'PASSWORD': 'MY-DB-PASSWORD',
    'DATABASE': 'MY-DB-NAME'
}
