development:
  adapter: postgresql
  host: localhost
  username: Trimble
  database: teslaworks-dev

test:
  adapter: postgresql
  host: localhost
  username: Trimble
  database: teslaworks-test

production:
  adapter: postgresql
  host: localhost
  username: Trimble
  database: teslaworks-production
